version: "3.8"
name: redis-counter
services:
   redis:
     image: redislabs/redismod
     container_name: redis
     ports:
       - '6379:6379'
   


   web:
        build: .
        image: jindouz/redis-counter:latest
        container_name: web
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
